[features]
seeds = false

[programs.devnet]
token_rewards_coupons = "ERUzTgkzMzXq738vac9e4sLGcPNSZAKQ9vuUuH87bY7b"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/griffin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
